# Docker Compose for Wordpress, Maria/MySQL & phpMyAdmin
version: '3.7'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD-secret}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-root}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD-secret}
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./database:/var/lib/mysql
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
  wordpress:
    image: wordpress:5.2.2-php7.2-apache
    depends_on:
      - db
    restart: always
    ports:
      - '${WORDPRESS_PORT:-80}:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD-secret}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
    volumes:
      - data_wordpress:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-content:/var/www/html/wp-content
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - '${PHPMYADMIN_PORT:-3000}:80'
  ftp:
    image: stilliard/pure-ftpd:latest
    depends_on:
      - wordpress
    restart: always
    ports:
      - '${FTP_PORT:-21}:21'
      - '${FTP_PASSIVE_PORT_FROM:-30000}-${FTP_PASSIVE_PORT_TO:-30009}:${FTP_PASSIVE_PORT_FROM:-30000}-${FTP_PASSIVE_PORT_TO:-30009}'
    environment:
      PUBLICHOST: 'localhost'
      FTP_USER_NAME: ${WORDPRESS_DB_USER:-root}
      FTP_USER_PASS: ${WORDPRESS_DB_PASSWORD-secret}
      FTP_USER_HOME: '/var/www/html'
      FTP_USER_UID: 33
      FTP_USER_GID: 33
      FTP_PASSIVE_PORTS: ${FTP_PASSIVE_PORT_FROM:-30000}:${FTP_PASSIVE_PORT_TO:-30009}
    volumes:
      - data_wordpress:/var/www/html
volumes:
  data_wordpress:
