# Docker Compose for Wordpress, Maria/MySQL & phpMyAdmin
version: '3.7'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD-secret}
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./database:/var/lib/mysql
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    restart: always
    ports:
      - '${WORDPRESS_PORT:-80}:80'
      - '443:443'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD-secret}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
    volumes:
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '${PHPMYADMIN_PORT:-3000}:80'
